name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:11
      - uses: actions/setup-node@v4
        with:
          node-version: 22.15.0
      - name: Enable Corepack
        run: corepack enable
      - name: Setup yarn
        run: corepack prepare yarn@1.22.19 --activate
      - name: Setup pnpm
        run: corepack prepare pnpm@8.14.3 --activate
      - name: Run tests
        uses: coactions/setup-xvfb@v1
        with:
          run: sbt scalafmtSbtCheck scalafmtCheckAll test scriptedSequentialPerModule
